### PR TITLE
add Snackbar completion

### PR DESCRIPTION
**Pull request by Axlchen**
xx.snack -> show a Snackbar
xx.snackaction ->show a Snackbar with an action

### CODE REVIEW

**Comment by takahirom** [comment]
Sorry, I'm late 🙇

**Comment by takahirom** [comment]
👀

**Comment by takahirom** [comment]
If you can , please use `getStaticPrefix()` for importing `Snackbar`.
https://github.com/takahirom/android-postfix-plugin/blob/master/src/main/java/com/kogitune/intellij/codeinsight/postfix/templates/surround/ToastTemplate.java#L49

**Comment by takahirom** [comment]
If you can, please add your completion to here.
https://github.com/takahirom/android-postfix-plugin#android-postfix-plugin
https://github.com/takahirom/android-postfix-plugin/blob/master/src/main/resources/META-INF/plugin.xml#L44

**Comment by Axlchen** [comment]
ok

**Comment by Axlchen** [comment]
I finish my work, take a look at it!

**Comment by Axlchen** [comment]
Done！

**Comment by takahirom** [comment]
Thank you for contributing!

**Pull request merged**
